paths:
  /api/products/:
    get:
      summary: Obtener todos los productos
      tags:
        - Productos
      responses:
        "200":
          description: Todos los productos fueron obtenidos correctamente
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#components/schemas/Product'
        "401":
          description: Error por falta de permisos
        "500":
          description: Error interno del servidor
  /api/products/{pid}:
    get:
      summary: Obtener un producto por el id
      tags:
        - Productos
      parameters:
        - name: pid
          in: path          
          required: true
          description: pid es el id del producto que desea obtener
          schema:
            $type: string
      responses:
        "200":
          description: Se obtuvo el producto correctamente
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor
    put:
      summary: Actualizar el producto por el id
      tags:
        - Productos
      parameters:
        - name: pid
          in: path          
          required: true
          description: pid es el id del producto que desea actualizar
          schema:
            $type: string
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'
      responses:
        "200":
          description: Se actualizo el producto correctamente
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor
    delete:
      summary: Eliminar el producto por el id
      tags:
        - Productos
      parameters:
        - name: pid
          in: path          
          required: true
          description: pid es el id del producto que desea eliminar
          schema:
            $type: string
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/deleteProduct'
      responses:
        "200":
          description: Se elimino el producto correctamente
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "500":
          description: Error interno del servidor


components:
  schemas:
    Product:
      type: object
      properties: 
        _id:
          type: ObjectId
          description: id del producto autogenerado por la base de datos
        title:
          type: string
          description: nombre del producto
        description:
          type: string
          description: descripción del producto
        price:
          type: string
          description: stock del producto
        stock:
          type: number
          description: stock del producto
      example:
        _id: ObjectId('hdqu324243d')
        title: Muzzarella
        description: Pizza con salsa de tomate y muzzarella
        price: $1500
        stock: 139 unidades
  requestBodies:
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: nombre del producto
        description:
          type: string
          description: descripcion del producto
        price:
          type: string
          description: precio del producto
        stock:
          type: number
          description: stock del producto
      example:
        title: pepe
        description: suarez
        price: $1500
        stock: 1234
    deleteProduct:
      type: object
      properties:
        title:
          type: string
          description: nombre del producto
        description:
          type: string
          description: descripcion del producto
        price:
          type: string
          description: precio del producto
        stock:
          type: number
          description: stock del producto
      example:
        title: pepe
        description: suarez
        price: $1500
        stock: 1234